(() => {
  const translations = new Map(Object.entries({
    "Gli appartamenti":"Apartments","La zona":"The area","Galleria":"Gallery","Recensioni":"Reviews","Contatti":"Contact",
    "Verifica disponibilità":"Check availability","Locri · Costa Ionica, Calabria":"Locri · Ionian Coast, Calabria",
    "Un'oasi di pace\nnel centro di Locri.":"An oasis of peace\nin the heart of Locri.","Un'oasi di pace":"An oasis of peace","nel centro di Locri.":"in the heart of Locri.","Relax, natura e autenticità nel cuore della Locride.":"Relax, nature and authenticity in the heart of the Locride.","Scopri gli appartamenti":"Discover the apartments",
    "◉ A due passi dal centro":"◉ Steps from the town centre","⌁ Wi-Fi veloce":"⌁ Fast Wi-Fi","❄ Aria condizionata":"❄ Air conditioning","♨ Cucina attrezzata":"♨ Equipped kitchen","⌂ Parcheggio":"⌂ Parking",
    "Due appartamenti appena rinnovati":"Two newly renovated apartments","Tutti i comfort":"All the comforts","Moderni, confortevoli e pensati per far vivere l'estate senza pensieri.":"Modern, comfortable spaces designed for a carefree summer stay.",
    "Aria condizionata":"Air conditioning","In ogni ambiente, per le notti più calde.":"Throughout the apartment, for the warmest nights.","Connessione veloce in tutta la casa.":"Fast connection throughout the apartment.","Per rilassarsi dopo una giornata di mare.":"To relax after a day by the sea.","Cucina attrezzata":"Equipped kitchen","Forno, lavastoviglie e macchina Nespresso incluse.":"Oven, dishwasher and Nespresso machine included.","Nuovi infissi":"New windows","Serramenti recenti, isolamento e silenzio.":"Recent windows for insulation and quiet.","Ambienti curati":"Well-kept interiors","Spazi confortevoli, puliti e ben arredati.":"Comfortable, clean and thoughtfully furnished spaces.",
    "Uno sguardo dentro casa":"A look inside","Gli interni":"The interiors","Scopri gli spazi dei nostri due appartamenti. Clicca su una soluzione per vedere tutte le foto.":"Explore our two apartments. Choose one to see all the photos.","1° appartamento":"1st apartment","2° appartamento":"2nd apartment","Bilocale":"One-bedroom apartment","Trilocale":"Two-bedroom apartment","1 camera · fino a 4 persone":"1 bedroom · up to 4 guests","2 camere · fino a 6 persone":"2 bedrooms · up to 6 guests","Guarda tutte le foto →":"View all photos →",
    "Luminoso, accogliente e ideale per coppie o piccole famiglie.":"Bright, welcoming and ideal for couples or small families.","Più spazio per famiglie e gruppi, con ambienti comodi e curati.":"More space for families and groups, with comfortable, thoughtfully designed interiors.",
    "Scegli il tuo":"Choose yours","Due appartamenti, per ogni gruppo":"Two apartments for every group","1° appartamento — Bilocale":"1st apartment — One-bedroom","2° appartamento — Trilocale":"2nd apartment — Two-bedroom","1 camera da letto":"1 bedroom","2 camere da letto":"2 bedrooms","1 bagno privato":"1 private bathroom","2 bagni privati":"2 private bathrooms","Divano letto":"Sofa bed","Max 4 persone":"Up to 4 guests","Max 6 persone":"Up to 6 guests","Perfetto per coppie o piccole famiglie.":"Perfect for couples or small families.","Ideale per famiglie numerose o gruppi di amici.":"Ideal for larger families or groups of friends.","Prezzi e disponibilità su richiesta, in base al periodo e al numero di persone.":"Prices and availability on request, depending on the dates and number of guests.",
    "Tutto quello che serve":"Everything you need","Servizi degli appartamenti":"Apartment amenities","Comfort pratici per sentirsi a casa anche in vacanza.":"Practical comforts to feel at home while on holiday.","❄️ Aria condizionata":"❄️ Air conditioning","♨️ Microonde":"♨️ Microwave","☕ Macchina da caffè":"☕ Coffee machine","🧺 Lavatrice":"🧺 Washing machine","🍽️ Stoviglie e utensili":"🍽️ Crockery & utensils","🛏️ Lenzuola":"🛏️ Bed linen","🧴 Asciugamani":"🧴 Towels","🍳 Cucina attrezzata":"🍳 Equipped kitchen","🧊 Frigorifero":"🧊 Refrigerator","💨 Asciugacapelli":"💨 Hair dryer","🔥 Piano cottura":"🔥 Hob","🥘 Pentole e padelle":"🥘 Pots & pans","🥂 Bicchieri e calici":"🥂 Glasses & wine glasses","🫖 Bollitore":"🫖 Kettle","🧼 Prodotti per la pulizia":"🧼 Cleaning products","🧻 Carta igienica":"🧻 Toilet paper","👕 Stendibiancheria":"👕 Drying rack","🧥 Armadio / guardaroba":"🧥 Wardrobe","🛋️ Zona soggiorno":"🛋️ Living area","🚿 Doccia":"🚿 Shower","🧴 Sapone mani":"🧴 Hand soap","🍽️ Lavastoviglie":"🍽️ Dishwasher","💻 Scrivania da lavoro":"💻 Work desk","Alcune dotazioni sono in fase di conferma: l’elenco verrà aggiornato prima della pubblicazione definitiva.":"Some amenities are still being confirmed; this list will be updated before final publication.",
    "Da fare, da vedere":"Things to do and see","La Locride da scoprire":"Discover the Locride","A piedi, in bici o in monopattino: cosa trovate intorno casa, in ordine di distanza.":"On foot, by bike or scooter: discover what is around the apartment, ordered by distance.","Snorkeling e SUP":"Snorkelling & SUP","Acque limpide e fondali ricchi di vita marina: la costa ideale per attività acquatiche in estate.":"Clear waters and marine life make this coast ideal for summer water activities.","I resti dell'antica città greca: templi, teatro e testimonianze di oltre 2.500 anni di storia.":"The remains of the ancient Greek city: temples, theatre and over 2,500 years of history.","Uno dei borghi più belli d'Italia, con la sua maestosa cattedrale, vicoli medievali e panorami mozzafiato.":"One of Italy's most beautiful villages, with its majestic cathedral, medieval lanes and breathtaking views.","Museo d'arte contemporanea immerso nella natura, con opere monumentali e mosaici.":"A contemporary art museum immersed in nature, with monumental works and mosaics.","Trekking nell'Aspromonte":"Hiking in Aspromonte","Escursioni tra boschi, cascate e panorami mozzafiato nel cuore del parco.":"Hikes through woods, waterfalls and breathtaking landscapes in the heart of the park.","Cascate di San Nicola":"San Nicola Waterfalls","Piscine naturali e sentieri ideali per una giornata di relax ed escursioni.":"Natural pools and trails, ideal for a relaxing day outdoors.",
    "La Calabria, un territorio unico":"Calabria, a unique land","Sapori della Locride":"Flavours of the Locride","Un clima mediterraneo e terreni fertili, uniti a saperi tradizionali tramandati di generazione in generazione.":"A Mediterranean climate and fertile land, combined with traditions passed down through generations.","Il celebre salume calabrese, originario di Spilinga: morbido e spalmabile, su pane caldo o nei sughi.":"The famous Calabrian speciality from Spilinga: soft and spreadable, perfect on warm bread or in sauces.","Uno dei prodotti naturali più riconosciuti della regione.":"One of the region's best-known natural products.","Simboli delle eccellenze casearie del territorio.":"Symbols of the area's outstanding cheese-making tradition.","Stocco alla mammolese":"Mammola-style stockfish","Stoccafisso ammollato, cucinato lentamente con pomodoro, patate, olive e capperi.":"Soaked stockfish slowly cooked with tomato, potatoes, olives and capers.","Tartufo di Pizzo":"Tartufo di Pizzo","Il dolce al cioccolato per eccellenza, offerto in vari gusti.":"The iconic chocolate dessert, available in several flavours.","Amari locali":"Local digestifs","Da provare a fine pasto, consigliati dal territorio.":"Local after-dinner digestifs worth trying.","Da assaggiare: Amaro Képhas, Amaro Rupes e Amaro del Capo.":"Try: Amaro Képhas, Amaro Rupes and Amaro del Capo.",
    "Disponibilità in tempo reale":"Real-time availability","Hai già in mente le date?":"Already have your dates in mind?","Scegli l’appartamento e consulta subito le disponibilità aggiornate dai nostri calendari.":"Choose an apartment and instantly check the latest availability from our calendars.",
    "Dicono di noi":"Guest reviews","Un soggiorno da ricordare":"A stay to remember","Questi testi sono esempi grafici: sostituiscili con recensioni reali degli ospiti prima della pubblicazione.":"These are sample review texts for layout purposes. Replace them with genuine guest reviews before publishing.","Recensione precedente":"Previous review","Recensione successiva":"Next review",
    "“Appartamento curato, luminoso e molto comodo per muoversi a Locri. Andrea è stato disponibile e ci siamo sentiti subito a casa.”":"“A bright, well-kept apartment in a very convenient location for exploring Locri. Andrea was helpful and made us feel at home straight away.”","“Posizione pratica, ambienti puliti e cucina ben organizzata. Ottima base per scoprire il mare e i borghi della Locride.”":"“Convenient location, clean rooms and a well-organised kitchen. A great base for discovering the coast and villages of the Locride.”","“Abbiamo apprezzato soprattutto la tranquillità e gli spazi. Il soggiorno è stato semplice da organizzare e molto piacevole.”":"“We especially appreciated the peace and the generous spaces. The stay was easy to organise and very enjoyable.”","“Una soluzione accogliente per qualche giorno in Calabria: casa confortevole, atmosfera rilassata e tutto il necessario a portata di mano.”":"“A welcoming place for a few days in Calabria: a comfortable home, relaxed atmosphere and everything we needed close at hand.”",
    "Il vostro host":"Your host","Andrea vi dà il benvenuto":"Andrea welcomes you","Situata a due passi dal centro di Locri, questa oasi di pace è stata creata per permettervi di riposarvi e ritrovare la tranquillità. Speriamo che vi piaccia. Benvenuti a casa vostra!":"Just steps from the centre of Locri, this peaceful oasis was created to help you rest and unwind. We hope you enjoy it. Welcome to your home away from home!","La vostra soddisfazione è la nostra priorità e siamo lieti di contribuire al successo del vostro soggiorno.":"Your satisfaction is our priority and we are delighted to help make your stay a success.",
    "Prenota il tuo soggiorno":"Plan your stay","Scrivi ad Andrea":"Contact Andrea","Per informazioni, prezzi e disponibilità: rispondiamo il prima possibile.":"For information, prices and availability, we reply as soon as possible.","Telefono":"Phone","Disponibili per informazioni su prezzi, periodi liberi e per organizzare l'arrivo.":"Contact us for prices, available dates and arrival arrangements.","Scrivici per foto aggiuntive, prezzi settimanali e disponibilità.":"Email us for additional photos, weekly rates and availability.",
    "Dove siamo":"Location","Nel cuore di Locri":"In the heart of Locri","Paradiso di Nosside si trova a Locri, in una posizione comoda per vivere il centro e raggiungere il mare.":"Paradiso di Nosside is in Locri, conveniently located for enjoying the town centre and reaching the sea.","Apri in Google Maps":"Open in Google Maps","Paradiso di Nosside · Locri, Calabria":"Paradiso di Nosside · Locri, Calabria","Il nome omaggia Nosside, poetessa greca nata a Locri nel IV sec. a.C.":"The name honours Nossis, the Greek poet born in Locri in the 4th century BC.",
    "Scopri tutti gli ambienti dell'appartamento.":"Explore every room in the apartment.","Scegli l’appartamento":"Choose an apartment","Quale appartamento preferisci?":"Which apartment do you prefer?","Seleziona una soluzione: caricheremo subito le disponibilità aggiornate da Google Calendar.":"Choose an apartment and we’ll load the latest availability from Google Calendar.","1 camera · 1 bagno · divano letto · max 4 persone":"1 bedroom · 1 bathroom · sofa bed · up to 4 guests","2 camere · 2 bagni · divano letto · max 6 persone":"2 bedrooms · 2 bathrooms · sofa bed · up to 6 guests","Vedi disponibilità →":"View availability →","← Cambia appartamento":"← Change apartment","Disponibilità aggiornata":"Updated availability","Disponibile":"Available","Occupato":"Booked","Controllo il calendario…":"Checking the calendar…","Fino a 4 persone":"Up to 4 guests","Fino a 6 persone":"Up to 6 guests","Ospiti":"Guests","Conferma queste date":"Confirm these dates","Periodo disponibile":"Dates available","Richiedi il preventivo":"Request a quote","Nome e cognome":"Full name","Messaggio":"Message","Acconsento all'uso dei dati per rispondere a questa richiesta.":"I consent to the use of my data to respond to this request.","Invia richiesta":"Send request","Grazie per averci contattato":"Thank you for contacting us","Richiesta ricevuta!":"Request received!","Abbiamo ricevuto la tua richiesta di preventivo. Ti risponderemo al più presto con tutte le informazioni per il tuo soggiorno al Paradiso di Nosside.":"We have received your quote request. We’ll get back to you as soon as possible with all the information for your stay at Paradiso di Nosside.","Controlla anche la cartella spam o posta indesiderata per non perdere la nostra risposta.":"Please also check your spam or junk folder so you don’t miss our reply.","Scrivici su WhatsApp":"Message us on WhatsApp","Chiudi":"Close",
    "Seleziona check-in e check-out direttamente sul calendario":"Select check-in and check-out directly on the calendar","Disponibilità — Bilocale":"Availability — One-bedroom","Disponibilità — Trilocale":"Availability — Two-bedroom","Controllo finale delle date…":"Final date check…","Inserisci date valide.":"Please enter valid dates.","Queste date includono almeno un giorno già occupato. Scegli un altro periodo.":"These dates include at least one booked day. Please choose another period.","Questo periodo non è più disponibile. Il calendario è stato aggiornato.":"These dates are no longer available. The calendar has been updated.","Periodo disponibile! Completa la richiesta qui sotto.":"Dates available! Complete your request below.","Servizio momentaneamente non disponibile.":"Service temporarily unavailable.","Invio in corso…":"Sending…","Invio non riuscito. Riprova.":"Could not send. Please try again.","Impossibile caricare le disponibilità.":"Unable to load availability.","Mese precedente":"Previous month","Mese successivo":"Next month"
  }));
  const months={gennaio:'January',febbraio:'February',marzo:'March',aprile:'April',maggio:'May',giugno:'June',luglio:'July',agosto:'August',settembre:'September',ottobre:'October',novembre:'November',dicembre:'December'};
  const textOriginal=new WeakMap(), attrOriginal=new WeakMap();
  let lang=localStorage.getItem('nosside-lang')==='en'?'en':'it';
  const normalize=s=>s.replace(/\s+/g,' ').trim();
  function translateString(raw){
    const key=normalize(raw); if(translations.has(key)) return translations.get(key);
    const m=key.match(/^(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre) (\d{4})$/i); if(m) return `${months[m[1].toLowerCase()]} ${m[2]}`;
    return raw;
  }
  function process(root=document){
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let n;
    while(n=walker.nextNode()){
      if(!n.parentElement || ['SCRIPT','STYLE'].includes(n.parentElement.tagName) || !normalize(n.nodeValue)) continue;
      if(!textOriginal.has(n)) textOriginal.set(n,n.nodeValue);
      const orig=textOriginal.get(n); n.nodeValue=lang==='en'?translateString(orig):orig;
    }
    const els=(root.querySelectorAll?[root,...root.querySelectorAll('*')]:[]).filter(Boolean);
    for(const el of els){
      for(const a of ['placeholder','aria-label','title','alt']) if(el.hasAttribute?.(a)){
        let rec=attrOriginal.get(el); if(!rec){rec={};attrOriginal.set(el,rec)} if(!(a in rec)) rec[a]=el.getAttribute(a);
        el.setAttribute(a,lang==='en'?translateString(rec[a]):rec[a]);
      }
    }
    document.documentElement.lang=lang;
    document.title=lang==='en'?'Paradiso di Nosside — Holidays in Locri':'Paradiso di Nosside — Estate a Locri';
    const meta=document.querySelector('meta[name="description"]'); if(meta) meta.content=lang==='en'?'Holiday apartments in Locri on Calabria’s Ionian coast. One- and two-bedroom apartments close to the town centre.':'Appartamenti in affitto a Locri, sulla costa ionica della Calabria. Bilocale e trilocale a due passi dal centro.';
    const b=document.querySelector('#lang-toggle'); if(b){b.textContent=lang==='en'?'IT':'EN';b.setAttribute('aria-label',lang==='en'?'Passa all’italiano':'Switch to English')}
  }
  function setLang(next){lang=next;window.NOSSIDE_LANG=lang;localStorage.setItem('nosside-lang',lang);process(document)}
  window.NOSSIDE_LANG=lang; window.nossideTranslate=()=>process(document);
  document.addEventListener('DOMContentLoaded',()=>{process(document);document.querySelector('#lang-toggle')?.addEventListener('click',()=>setLang(lang==='it'?'en':'it'));new MutationObserver(ms=>{for(const m of ms) for(const node of m.addedNodes) if(node.nodeType===1||node.nodeType===3) process(node.nodeType===1?node:node.parentElement)}).observe(document.body,{childList:true,subtree:true});});
})();
